apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: production-env
  region: us-west-2

# Define the VPC and its subnets
vpc:
  id: vpc-0db14f7fc1a2d8f6b
  subnets:
    public:
      us-west-2a:
        id: subnet-0ddb377c6e21c9f8b # Public subnet in us-west-2a
      us-west-2c:
        id: subnet-0ff0ba2093fd40b69 # Public subnet in us-west-2c
    private:
      us-west-2d:
        id: subnet-013e0287e34108157 # Private subnet in us-west-2d
      us-west-2b:
        id: subnet-0890865580e07e95f # Private subnet in us-west-2b


# Define the node groups
nodeGroups:
  - name: general
    instanceType: t3.small
    desiredCapacity: 2
    labels: 
      role: general
    volumeSize: 40 # GiB
    privateNetworking: true
